Improved type annotations (#49)
This commit fixes a mypy error

```
tests/conftest.py:37: error: The return type of a generator function should be "Generator" or one of its supertypes
Found 1 error in 1 file (checked 24 source files)
```

and adds missing annotations to API clients (TodoistAPI and TodoistAPIAsync).